---
dependency:
  name: galaxy
lint: |
  set -e
  ansible-lint .
driver:
  name: podman
platforms:
  - name: instance
    image: docker.io/redhat/ubi8:latest
    pre_build_image: true
    published_ports:
      - 0.0.0.0:18080:8080/tcp
provisioner:
  name: ansible
verifier:
  name: ansible
