---
dependency:
  name: galaxy
lint: |
  set -e
  ansible-lint . -x meta-incorrect,meta-no-info,package-latest,risky-file-permissions,fqcn-builtins,experimental
driver:
  name: podman
platforms:
  - name: instance
#    image: docker.io/redhat/ubi8:latest
    image: docker.io/rockylinux/rockylinux:8
    pre_build_image: true
    published_ports:
      - 0.0.0.0:18080:8080/tcp
provisioner:
  name: ansible
verifier:
  name: ansible
